### ISSUE TITLE
LightAPI not working on latest 1.19.2 Paper

### ISSUE THREAD

**Issue by ProdByPengu** [BeYkeRYkt/LightAPI#38] opened 2022-09-28 04:32 UTC
LightAPI doesn't work on the latest 1.19.2 Paper

```
[00:30:41 INFO]: [LightAPI] Enabling LightAPI vbukkit-5.3.0 (build SNAPSHOT)
[00:30:41 INFO]: <LightAPI>: [INFO] Initializing LightAPI...
[00:30:41 WARN]: java.lang.RuntimeException: (NoSuchFieldException) e
[00:30:41 WARN]:        at LightAPI.jar//ru.beykerykt.minecraft.lightapi.bukkit.internal.handler.craftbukkit.nms.v1_19_R1.VanillaNMSHandler.toRuntimeException(VanillaNMSHandler.java:81)
[00:30:41 WARN]:        at LightAPI.jar//ru.beykerykt.minecraft.lightapi.bukkit.internal.handler.craftbukkit.nms.v1_19_R1.VanillaNMSHandler.onInitialization(VanillaNMSHandler.java:187)
[00:30:41 WARN]:        at LightAPI.jar//ru.beykerykt.minecraft.lightapi.bukkit.internal.handler.craftbukkit.nms.v1_19_R1.StarlightNMSHandler.onInitialization(StarlightNMSHandler.java:167)
[00:30:41 WARN]:        at LightAPI.jar//ru.beykerykt.minecraft.lightapi.bukkit.internal.BukkitPlatformImpl.initialization(BukkitPlatformImpl.java:229)
[00:30:41 WARN]:        at LightAPI.jar//ru.beykerykt.minecraft.lightapi.common.LightAPI.initialization(LightAPI.java:88)
[00:30:41 WARN]:        at LightAPI.jar//ru.beykerykt.minecraft.lightapi.bukkit.BukkitPlugin.onEnable(BukkitPlugin.java:70)
[00:30:41 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[00:30:41 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[00:30:41 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
[00:30:41 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565)
[00:30:41 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479)
[00:30:41 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636)
[00:30:41 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422)
[00:30:41 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
[00:30:41 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1100)
[00:30:41 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[00:30:41 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[00:30:41 WARN]: Caused by: java.lang.NoSuchFieldException: e
[00:30:41 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
[00:30:41 WARN]:        at LightAPI.jar//ru.beykerykt.minecraft.lightapi.bukkit.internal.handler.craftbukkit.nms.v1_19_R1.VanillaNMSHandler.onInitialization(VanillaNMSHandler.java:175)
[00:30:41 WARN]:        ... 15 more
[00:30:41 WARN]: java.lang.IllegalStateException: Initialization failed! Code: -1
[00:30:41 WARN]:        at LightAPI.jar//ru.beykerykt.minecraft.lightapi.common.LightAPI.initialization(LightAPI.java:96)
[00:30:41 WARN]:        at LightAPI.jar//ru.beykerykt.minecraft.lightapi.bukkit.BukkitPlugin.onEnable(BukkitPlugin.java:70)
[00:30:41 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[00:30:41 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[00:30:41 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
[00:30:41 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565)
[00:30:41 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479)
[00:30:41 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636)
[00:30:41 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422)
[00:30:41 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
[00:30:41 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1100)
[00:30:41 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[00:30:41 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[00:30:41 INFO]: [LightAPI] Disabling LightAPI vbukkit-5.3.0 (build SNAPSHOT)
[00:30:41 INFO]: <LightAPI>: [INFO] Shutdown LightAPI...
```

**Comment by ttt0** [comment] 2022-09-28 20:03
I have the same problem unfortunately

**Comment by mike112112** [comment] 2022-09-28 20:33
having compatibility mode enabled seems to work with papermc build #177

<LightAPI>: [INFO] Initializing LightAPI...
<LightAPI>: [INFO] Compatibility mode is enabled
<LightAPI>: [DEBUG] ru.beykerykt.minecraft.lightapi.bukkit.internal.chunks.observer.sched.BukkitScheduledChunkObserverImpl is started!
<LightAPI>: [DEBUG] ru.beykerykt.minecraft.lightapi.bukkit.internal.engine.sched.BukkitScheduledLightEngineImpl is started!
<LightAPI>: [INFO] Metrics is enabled!
<LightAPI>: [INFO] LightAPI initialized!

**Comment by ProdByPengu** [comment] 2022-09-28 20:38
doesn't actually work though, even with compatibility mode

**Comment by mike112112** [comment] 2022-09-28 20:41
![2022-09-28_22 40 33](https://user-images.githubusercontent.com/61821130/192884462-882041bf-ae76-4034-b2a2-857eff78006c.png)

**Comment by marcelschoen** [comment] 2022-09-29 20:09
Wait, it actually works for me on PaperMC 1.19.2, with the following two configuration settings:

enable-compatibility-mode: true
force-enable-legacy: true

When I walk around with a torch in my hand, my surrounding is dynamically illuminated (with the additional plugin "Dynamic Lights" installed).

**Comment by nhanledev** [comment] 2022-10-01 07:55
What does paper change to cause this issue? I am having this problem too

**Comment by mike112112** [comment] 2022-10-01 08:02
the "Rewrite chunk system" could be a possibility

**Comment by Boy0000** [comment] 2022-10-01 08:09
The paper update to Rewrite chunk system removes some old nms methods which lightapi used
`[00:30:41 WARN]: Caused by: java.lang.NoSuchFieldException: e` hence this warning in the logfile

**Comment by 00Hrtz** [comment] 2022-10-03 18:52
confirmed paper 1.19.2 #193

While marcelschoen's workaround is appreciated, adding an extra plugin i don't need is not something i wish to do.

Edit: setting enable-compatibility-mode:  to true fixed it.

**Comment by mschoenUsp** [comment] 2022-10-04 07:44
I think you misunderstood. The second plugin has nothing to do with it, but this one is an amazing addition. "Darker Nights" makes the nights darker by decreasing the block light level in a large radius; makes nights really scary. And "Dynamic Lights", which relies on "Light API", allows to have a torch in your hand which dynamically illuminates your surroundings. All this combined is amazing for a survival server.

**Comment by Randall-Rut** [comment] 2022-10-07 05:14
hello it is true that it is fixed by activating the compatibility mode but in the latest purpur compilations, now it does not turn off the plugin when the server is shutting down .. so you have to kill and this makes the automatic restarts useless, so now has 2 compatibility issues with 1.19.2

**Comment by fnrcum** [comment] 2022-10-10 09:12
Compatibility mode seems to set light levels constantly instead of hijaking the chunks as before. This will def make it take a performance hit

**Comment by MelonCraftDE** [comment] 2022-10-23 20:33
im sure its not gonna be fixed in the next months, dev is inactive

**Comment by thefourcraft** [comment] 2022-11-29 10:41
> im sure its not gonna be fixed in the next months, dev is inactive

it's a open source, anyone can fix it (assuming they have some java knowledge) 😉

**Comment by mschoenUsp** [comment] 2022-11-29 10:55
Fair point, but one also needs a good enough understanding of the Spigot APIs and how lighting works... Maybe I'll take a look, but I'm not sure I have the necessary knowledge. And then there's also the question of how well-written/clean his code is...

**Comment by Boy0000** [comment] 2022-11-29 20:43
I would if this project wasnt maven + spigot nms + 1.13-1.19. the holy trifecta of tomfuckery lol
it should be dead simple, seeing as modelengine had the issue and fixed it real quick, same with mccosmetics

**Comment by mschoenUsp** [comment] 2022-11-30 08:30
Having worked with Maven for ever since 1.0, that's the least of my problems. I know it inside out. But Spigot / NMS, not so much... However, I think that support for older versions could be skipped, to be honest. I mean at this point, if someone runs an older server, they can just use an older release of the plugins. I would be fine with a clean break and a 1.19 only version.

**Comment by mschoenUsp** [comment] 2022-11-30 08:33
IMO, IF multi-version support is to be continued, it may be better to have multiple long-living branches in the GIT repo. This way, the code for each version can be much cleaner. If you make changes that make sense for the other versions too, you can just cherry-pick them. I'd prefer this over one branch with tons of complicated "if-elses" or interfaces with version-specific implementations etc.

**Comment by mschoenUsp** [comment] 2022-11-30 08:36
Guess it's time to spend some time on an NMS tutorial... https://www.spigotmc.org/threads/nms-tutorials-1-introduction-to-nms.204127/

**Comment by ahdg6** [comment] 2023-02-02 15:32
Probably caused by this PR: https://github.com/PaperMC/Paper/pull/8177
Some nms do not exist anymore since that pr, that's why LightAPI won't work on paper.

**Comment by IPECTER** [comment] 2023-03-24 06:00
@ahdg6 and everyone
Try this https://github.com/IPECTER/LighterAPI/releases/tag/5.4.0-SNAPSHOT

**LightAPI 1.13 ~ 1.19.4 Spigot & Paper**

**Comment by MelonCraftDE** [comment] 2023-03-24 11:39
Awesome!

IPECTER 이팩터 ***@***.***> schrieb am Fr., 24. März 2023, 07:01:

**Comment by BeYkeRYkt** [comment] 2024-01-05 14:56
Issue closed: LightAPI is no longer being maintained.

**Closed as completed by BeYkeRYkt** 2024-01-05 14:56 UTC
